version: "3.7"

services:
  frontend:
    container_name: frontend
    env_file: .env
    build:
      context: .
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "3000:80"
    restart: always
